# Site settings
title: WhitestormJS
email: alexbuzin88@gmail.com
url: whitestormjs.xyz
description: "WhitestormJS is a library to combine Three.Js with Cannon.js. It makes WebGL development easy."
skills: "WebGL support - THREE.JS - CANNON.JS"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Alexander Buzin
  location: Location / Email
  social: 3D LIBRARY
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/whitestormjs
  - title: facebook
    url: https://www.facebook.com/sasha.buzin.5
  - title: stack-overflow
    url: http://stackoverflow.com/users/5494315/alexander-buzin
  - title: bitbucket
    url: https://bitbucket.org/sasha240100/whitestormjs/
  - title: github
    url: https://github.com/sasha240100/whitestormjs/

# Postal address (add as many lines as necessary)
address:
  - line: Kiev, Ukraine
  - line: alexbuzin88@gmail.com

# Credits content
credits: 'Alexander Buzin, web-developer and web-design.'

# Build settings
markdown: kramdown
permalink: pretty

wikiToJekyll:

  # your user Github Name
  user_name: sasha240100

  # your repository Name
  repository_name: WhitestormJS

  # set your remote name. 'origin' is the default name set
  # when you do a 'git init'
  # if you changed this name be sure to change this parameter
  deploy_remote: "origin"

  # for an organization / user, publication branch is master
  # for a project, publication branch is gh-pages
  deploy_branch: "gh-pages"

  # wiki repository url
  # if you live this blank, it will be derived from you code
  # user_name and repository_name
  #   eg : wiki_repository_url = user_name/repository_name/wiki'
  #
  # If you're importing a wiki from another code repository
  # you MUST set this url
  #
  # IMPORTANT: no git@github.com: in front
  #            You MUST use the htpps:// url or it will
  #            cause a submodule error on github
  #
  # Example : https://github.com/userName/repositoryName.wiki.git

  wiki_repository_url: https://github.com/sasha240100/WhitestormJS.wiki.git # https://github.com/userName/repositoryName.wiki.git

  # wiki submodule folder
  # the underscore makes sure that this folder is ignored by Jekyll
  wiki_source: "_wiki"

  # wiki Jekyll generated pages destination folder
  wiki_dest: "wiki"

  # commit and push to Jekyll repository after wiki synchronisation
  commit_and_push: false

kramdown:
  input: GFM
